name: Deploy to Production

on:
  push:
    branches:
      - main  # Substitua por sua branch, se necessário

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Passo 2: Configurar a chave SSH para autenticação
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Usando a chave privada do Secret

      # Passo 3: Conectar ao servidor e rodar comandos de deploy
      - name: Deploy project via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}  # IP ou domínio
          username: ${{ secrets.SERVER_USERNAME }}  # Nome de usuário SSH no servidor
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Chave privada
          port: 22  # Porta SSH
          script: |
            # Passo 4: Comandos de deploy
            cd /var/www/curso-laravel-Michel  # Altere para o diretório do seu projeto
            git pull origin main  # Faz o pull das últimas mudanças
            composer install # Instala as dependências
            php artisan migrate --force  # Roda as migrações (forçado para produção)
            php artisan key:generate  # Gera a chave do aplicativo, se necessário
            php artisan db:seed --force  # Executa o seeder, se necessário
